name: Generate 2024 Contribution Snake

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate 2024 Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: VanshikaKumar1910
          outputs: |
            output/github-contribution-grid-snake-2024.svg?year=2024

      - name: Push 2024 snake to output folder
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Generate 2024 contribution snake"
          file_pattern: output/*
