name: Generate 2024 Contribution Snake

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate snake for 2024
        uses: Platane/snk@v3
        with:
          github_user_name: VanshikaKumar1910
          outputs: |
            output/snake-2024.svg
          years: 2024

      - name: Push generated files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Add 2024 contribution snake"
          file_pattern: output/*
